from .localization import Localization


class English(Localization):
    name = "English"
    _terms = {"this_language": name,
              "British": "British",
              "price": "Cost",
              "gold": "gold",
              "balance_teams": "Balance teams",
              "settings": "Settings",
              "bermuda": "You sail through the edge of the Bermuda triangle, but nothing happens.",
              "brigantine": "brigantine",
              "aiming": "Take aim!",
              "whalevsoctopus": "fights it",
              "title": "The Treasure of the Pirate King",
              "battle": "Battle",
              "leave_battle": "Leaving battlefield",
              "leave_battle_text": "Leaving the battlefield now makes you lose your entire crew and you will be "
                                   "stranded on the Forgotten Island. Are you sure that you leave now?",
              "battle_sink": "The enemy ship sunk.",
              "battle_lose": "You lost. The enemy captain put you ashore at the Forgotten Island.",
              "event_card": "Event card",
              "extra": "Pick an enemy team to target bonus attack.",
              "resolution": "Resolution",
              "land": "The sailors collect fruits and fowl on the island. If the value you rolled is unfavourable you "
                      "may roll again at the next turn.",
              "land_log": "You may roll again.",
              "tavern": "Tavern",
              "French": "French",
              "frigate": "frigate",
              "main_main": "Main menu",
              "galleon": "galleon",
              "shipwright": "Shipwright",
              "ship_spotted": "Ship spotted. What is your order?",
              "ship_spotted_fire": "Fire!",
              "ship_spotted_alvarez": "You can rearrange your man.",
              "ship_spotted_battle_starts": "Use a card or push the Battle button to fight.",
              "ship_spotted_let_them_flee": "Let them sail away",
              "ship_spotted_battle": "The battle begun. Form teams.",
              "ship_spotted_reward": "Your loot %i gold pieces%s.",
              "ship_spotted_reward2": " and a loot card.",
              "ship_spotted_pirate": "Ship spotted. She is on intercept course.",
              "ship_spotted_powder_storage": "The enemy ship got a hit to the powder store and exploded.",
              "ship_spotted_boarding": "Board her!",
              "ship_spotted_fleeing": "Run for it",
              "ship_spotted_fleeing_unsuccesful": "The hostile ship were faster than you and the enemy sailors are "
                                                  "boarding your ship.",
              "ship_spotted_parrot": "Your parrot brings you the treasure from the enemy ship.\\n",
              "ship_spotted_enemy_casualties": "The enemy lost %i sailor(s) due the cannonfire.",
              "ship_spotted_player_casualties": "You lost 2 sailors due the cannonfire.",
              "ship_spotted_enemy_sinking": "The enemy ship got a leak! It will sink in 3 turns.",
              "ship_name_player": "Your own ship",
              "ship_name_pirate0": "Black Scream",
              "ship_name_pirate1": "Black Freighter",
              "ship_name_pirate2": "Destiny",
              "ship_name_pirate3": "Groglord",
              "to_battle": "Pick up the fight",
              "Dutch": "Dutch",
              "info": "Message",
              "game": "Game",
              "loading_game": "Loadig game...",
              "loading_done": "Loadig game... Done!",
              "discard_game": "Game is already in progress. If you start a new one, all unsaved changes will be lost. "
                              "Are you sure you want to start a new game?",
              "discard_game_b": "Game is already in progress. If you load a saved one, all unsaved changes will be "
                                "lost. Are you sure you want to load a saved game?",
              "start_game": "Starting game...",
              "start_game_done": "Starting game... Done!",
              "turn_order": "Turn order:",
              "Pirate": "Pirate",
              "card_discard": "Discard it",
              "card_keep": "Keep card",
              "cards": "Cards",
              "done": "Done",
              "port": "Port",
              "miss_turn": "I miss a turn (%i turns left)",
              "miss_turn_last_time": "I miss a turn",
              "treasure": "Treasure",
              "treasure_card": "Treasure card",
              "dig_for_treasure": "You can dig for treasuere next turn.",
              "dig_for_treasure_label": "You can dig for treasuere next turn.",
              "dig_for_treasure_question": "You can sail away or stay to look for treasure. Do you want to stay?",
              "dig_for_treasure_nothing": "Bad luck: you found nothing.",
              "governor": "Governor",
              "governor_punish": "As a pirate you are senteced to inprisonment for %i turn(s). Don't hope such mercy "
                                 "if you are caught plundering our ships again.",
              "governor_reward": "The govenor gives you %i gold(s) as a reward for sinking enemy ships.",
              "crew": "Crew",
              "crew_new": "Hire new members:",
              "crew_ship_full": "Ship is fully manned.",
              "crew_port_empty": "No one to hire.",
              "crew_no_money": "You have not enough treasure.",
              "crew_hire": "Hire",
              "men_count": "%i sailor(s) in %i team(s)",
              "play_leviathan": "Play leviathan",
              "already_bought": "Already bought",
              "name_missing": "Player {} has no name.",
              "fight": "Fight!",
              "language": "Language",
              "scores": "Scores",
              "Spanish": "Spanish",
              "translation_missing": "[Translation is missing.]",
              "sailors_to_hire": "Sailors to hire",
              "castaway_no_hope": "You could not get away from the island in this round.",
              "castaway_success": "A ship picked you up from the island and brought you to %s.",
              "calm": "You miss a turn because of the dead calm.",
              "color_missing": "{} has picked no color.",
              "sirens": "You lost %i sailors.",
              "sirens_skipped": "You have the card.",
              "schooner": "schooner",
              "taino_one": "A friendly native man joined your crew.",
              "taino_none": "Some natives wave you from the shores.",
              "taino_some": "%i friendly native men joined your crew.",
              "new_turn": "'%s's turn.",
              "new_resolution": "Resolution is set to",
              "new_language": "English is set as display language.",
              "driftwood": "Nothing useful could be found among the driftwood.",
              "driftwood_success": "Treasure worth of one gold found among the driftwood.",
              "defeated_by_kraken": "The kraken defeated you.",
              "casualties_of_kraken": "The Kraken killed %i of your saliros before you could fight it off.",
              "storm_miss_turn": "The storm shred the sails. Miss a turn while your crew patch it.",
              "storm_success": "Your ship sails further because of the storm's wind.",
              "storm_sail_damage": "The storm shred the sails. Fortunately you had some spare sails at the cargo "
                                   "hold.",
              "flag_invalid": "{} has picked no valid flag.",
              "flag_missing": "{} has picked no flag.",
              "mutiny_succeeded": "You are put ashore on the Forgotten Island.",
              "mutiny_suppressed": "You manage to calm you crew down. The crewman who plotted the mutiny is put "
                                   "ashore on an island.",
              'apply': 'Apply',
              'load_saved_game': 'Load saved game',
              'exit': 'Exit',
              'save': 'Save game',
              'save_and_exit': 'Save & exit',
              'name_label': 'Name:',
              'start_button': 'Start',
              'color_label': 'Color:',
              'full_screen': 'Full screen',
              'new_game': 'New Game',
              'flag_label': 'Flag:'
              }
