from .localization import Localization


class Hungarian(Localization):
    name = "Magyar"
    _terms = {
        "this_language": name,
        "British": "angol",
        "price": "Ár",
        "gold": "arany",
        "balance_teams": "Csapatok elosztása",
        "settings": "Beállítások",
        "bermuda": "Utad során érinted a Bermuda-háromszöget, de semmi érdekes nem történik.",
        "brigantine": "brigantin",
        "aiming": "Válassz célpontot!",
        "whalevsoctopus": "megküzd vele",
        "title": "A kalózkirály kincse",
        "battle": "Csata",
        "leave_battle": "Csata elhagyása",
        "leave_battle_text": "Ha bezárod ezt a képernyőt, elveszíted a matrózaid, és a száműzöttek szigetére kerülsz. "
                             "Biztosan ezt szeretnéd?",
        "battle_sink": "Az ellenséges hajó elsüllyedt.",
        "battle_lose": "Veszítettél. Ellenfeleid fogságba ejtettek, és a Száműzöttek szigetén tettek partra.",
        "event_card": "Eseménykártya",
        "extra": "Válaszd ki, melyik ellenséges csapat ellen indítasz extra támadást!",
        "resolution": "Felbontás",
        "land": "Amíg a többiek vannak soron, matrózaid gyümölcsöket és szárnyasokat gyűjtenek be az érintetlen "
                "szigetről. A friss koszt fellelkesíti őket, ezért, ha a következő körben hajózáshoz dobott érték "
                "kedvezőtlen, egyszer újra dobhatsz helyette.",
        "land_log": "Újra dobhatsz ehelyett.",
        "tavern": "Fogadó",
        "French": "francia",
        "frigate": "fregatt",
        "main_main": "Főmenü",
        "galleon": "galleon",
        "shipwright": "Hajóács",
        "ship_spotted": "Hajó a láthatáron! Mit tegyen a legénység?",
        "ship_spotted_fire": "Tűz!",
        "ship_spotted_alvarez": "Most megváltoztathatod a csapatok felállását.",
        "ship_spotted_battle_starts": "Játssz ki egy kártyát, vagy kattints az alábbi gombra a harchoz.",
        "ship_spotted_let_them_flee": "Hagyjuk futni",
        "ship_spotted_battle": "Kezdődik a harc. Oszd be csapatokba az embereidet.",
        "ship_spotted_reward": "Zsákmányod %i arany%s.",
        "ship_spotted_reward2": " és egy kincskártya",
        "ship_spotted_pirate": "Hajó a láthatáron! Egyenesen felénk tart!",
        "ship_spotted_powder_storage": "Az ellenséges hajó lőporraktára felrobbant.",
        "ship_spotted_boarding": "Csáklyázzuk meg!",
        "ship_spotted_fleeing": "Menekülés",
        "ship_spotted_fleeing_unsuccesful": "Az ellenséges hajó beért, és megtámadott.",
        "ship_spotted_parrot": "Papagájod megszerezte az ellenséges hajó kincsét!\\n",
        "ship_spotted_enemy_casualties": "Az ellenfél %i matrózt veszített az ágyúzás során.",
        "ship_spotted_player_casualties": "2 matrózt vesztettél az ágyúzás során.",
        "ship_spotted_enemy_sinking": "Az ellenfél hajója léket kapott. 3 körön belül elsüllyed!",
        "ship_name_player": "Saját hajód",
        "ship_name_pirate0": "Fekete Sikoly",
        "ship_name_pirate1": "Vérszínű Bárka",
        "ship_name_pirate2": "Végzet",
        "ship_name_pirate3": "Grogbáró",
        "to_battle": "Megküzdünk vele",
        "Dutch": "holland",
        "info": "Üzenet",
        "game": "Játék",
        "loading_game": "Játék betöltése...",
        "loading_done": "Játék betöltése... Kész!",
        "discard_game": "Már folyamatban van egy játék. Ha újat indítasz, az előző játékból minden elvész, ami nem "
                        "volt mentve. Biztosan új játékot kezdesz?",
        "discard_game_b": "Már folyamatban van egy játék. Ha betöltesz egy másikat, a jelenlegi játékból minden "
                          "elvész, ami nincs mentve. Biztosan a betöltést választod?",
        "start_game": "Játék indítása...",
        "start_game_done": "Játék indítása... Kész!",
        "turn_order": "A játékosok sorrendje:",
        "Pirate": "kalóz",
        "card_discard": "Lap eldobása",
        "card_keep": "Lap megtartása",
        "cards": "Kártyák",
        "done": "Kész",
        "port": "Kikötő",
        "miss_turn": "Kimaradok (még %i kör)",
        "miss_turn_last_time": "Kimaradok",
        "treasure": "Kincs",
        "treasure_card": "Kincskártya",
        "dig_for_treasure": "Kincset áshatsz a következő körben.",
        "dig_for_treasure_label": "A kincses szigeten",
        "dig_for_treasure_question": "Továbbmehetsz, vagy átkutathatod kincsért a szigetet. Maradsz a szigeten?",
        "dig_for_treasure_nothing": "Most nem jártál sikerrel.",
        "governor": "Kormányzó",
        "governor_punish": "A birodalom hajóinak elsüllyesztéséért %i körből kimaradsz.",
        "governor_reward": "Az esüllyesztett hajókért a kormányzó %i arany jutalomban részesít.",
        "crew": "Legénység",
        "crew_new": "Új matrózok felbérelése:",
        "crew_ship_full": "A hajó megtelt.",
        "crew_port_empty": "Nincs kit felbérelni.",
        "crew_no_money": "Nincs pénz új matrózokra.",
        "crew_hire": "Felbérel",
        "men_count": "%i matróz %i csapatban",
        "play_leviathan": "Kijátszom a leviatánt",
        "already_bought": "Már megvetted",
        "name_missing": "{}. játékos névtelen maradt!",
        "fight": "Összecsapás!",
        "language": "Nyelv",
        "scores": "Pontszámok",
        "Spanish": "spanyol",
        "translation_missing": "[Hiányzik a megfelelő szöveg fordítása.]",
        "sailors_to_hire": "Felbérelhető matrózok",
        "castaway_no_hope": "Ebben a körben nem tudsz megszabadulni a szigetről.",
        "castaway_success": "Egy hajó felvett a szigetről, és %s kikötőjébe vitt.",
        "calm": "A szélcsend miatt egy körből kimaradsz.",
        "color_missing": "{} még nem választott színt!",
        "sirens": "Vesztettél %i matrózt.",
        "sirens_skipped": "Tiéd a lap, harcban kijátszható.",
        "schooner": "szkúner",
        "taino_one": "Egy barátságos benszülött csatlakozott.",
        "taino_none": "A benszülöttek barátságosan üdvzölnek.",
        "taino_some": "%i barátságos benszülött csatlakozott.",
        "new_turn": "%s köre jön.",
        "new_resolution": "A beállított új felbontás:",
        "new_language": "A magyar nyelvet állítottad be.",
        "driftwood": "Az uszadékban semmi hasznosat nem találsz.",
        "driftwood_success": "Egy arany értékű kincset találtál.",
        "defeated_by_kraken": "A kraken legyőzött.",
        "casualties_of_kraken": "A kraken elragadta %i matrózod, mielőtt legyőzted.",
        "storm_miss_turn": "A vihar tönkretette a vitorlázatot. Kimaradsz egy körből, amíg a legénység megfoltozza.",
        "storm_success": "A viharos szél tovább röpíti hajódat.",
        "storm_sail_damage": "A vihar tönkretette a vitorlázatot. Még szerencse, hogy a raktérben volt "
                             "tartalékvitorla.",
        "flag_invalid": "{} érvénytelen zászlót választott!",
        "flag_missing": "{} még nem választott zászlót!",
        "mutiny_succeeded": "A legénység partra tesz egy szigeten.",
        "mutiny_suppressed": "Egy hangzatos beszéddel magad mögé állítod a matrózokat, és a főkolompost kiteszitek "
                             "egy szigetre.",
        "apply": "Alkalmaz",
        "load_saved_game": "Játék folytatása",
        "exit": "Kilépés",
        "save": "Játék mentése",
        "save_and_exit": "Mentés és kilépés",
        "name_label": "Név:",
        "start_button": "Start",
        "color_label": "Szín:",
        "full_screen": "Teljes képernyő",
        "new_game": "Új játék",
        "flag_label": "Zászló:"
    }
