from .localization import Localization


class Hungarian(Localization):
    name = "Magyar"
    _terms = {
        "this_language": name,
        "British": "angol",
        "price": "Ár",
        "gold": "arany",
        "balance_teams": "Csapatok elosztása",
        "settings": "Beállítások",
        "bermuda": "Utad során érinted a Bermuda-háromszöget, de semmi érdekes nem történik.",
        "brigantine": "brigantin",
        "aiming": "Válassz célpontot!",
        "whalevsoctopus": "megküzd vele",
        "title": "A kalózkirály kincse",
        "battle": "Csata",
        "leave_battle": "Csata elhagyása",
        "leave_battle_text": "Ha bezárod ezt a képernyőt, elveszíted a matrózaid, és a száműzöttek szigetére kerülsz. "
                             "Biztosan ezt szeretnéd?",
        "battle_sink": "Az ellenséges hajó elsüllyedt.",
        "battle_lose": "Veszítettél. Ellenfeleid fogságba ejtettek, és a Száműzöttek szigetén tettek partra.",
        "event_card": "Eseménykártya",
        "extra": "Válaszd ki, melyik ellenséges csapat ellen indítasz extra támadást!",
        "resolution": "Felbontás",
        "land": "Amíg a többiek vannak soron, matrózaid gyümölcsöket és szárnyasokat gyűjtenek be az érintetlen "
                "szigetről. A friss koszt fellelkesíti őket, ezért, ha a következő körben hajózáshoz dobott érték "
                "kedvezőtlen, egyszer újra dobhatsz helyette.",
        "land_log": "Újra dobhatsz ehelyett.",
        "tavern": "Fogadó",
        "French": "francia",
        "frigate": "fregatt",
        "main_main": "Főmenü",
        "galleon": "galleon",
        "shipwright": "Hajóács",
        "ship_spotted": "Hajó a láthatáron! Mit tegyen a legénység?",
        "ship_spotted_fire": "Tűz!",
        "ship_spotted_alvarez": "Most megváltoztathatod a csapatok felállását.",
        "ship_spotted_battle_starts": "Játssz ki egy kártyát, vagy kattints az alábbi gombra a harchoz.",
        "ship_spotted_let_them_flee": "Hagyjuk futni",
        "ship_spotted_battle": "Kezdődik a harc. Oszd be csapatokba az embereidet.",
        "ship_spotted_reward": "Zsákmányod %i arany%s.",
        "ship_spotted_reward2": " és egy kincskártya",
        "ship_spotted_pirate": "Hajó a láthatáron! Egyenesen felénk tart!",
        "ship_spotted_powder_storage": "Az ellenséges hajó lőporraktára felrobbant.",
        "ship_spotted_boarding": "Csáklyázzuk meg!",
        "ship_spotted_fleeing": "Menekülés",
        "ship_spotted_fleeing_unsuccesful": "Az ellenséges hajó beért, és megtámadott.",
        "ship_spotted_parrot": "Papagájod megszerezte az ellenséges hajó kincsét!\\n",
        "ship_spotted_enemy_casualties": "Az ellenfél %i matrózt veszített az ágyúzás során.",
        "ship_spotted_player_casualties": "2 matrózt vesztettél az ágyúzás során.",
        "ship_spotted_enemy_sinking": "Az ellenfél hajója léket kapott. 3 körön belül elsüllyed!",
        "ship_name_player": "Saját hajód",
        "ship_name_pirate0": "Fekete Sikoly",
        "ship_name_pirate1": "Vérszínű Bárka",
        "ship_name_pirate2": "Végzet",
        "ship_name_pirate3": "Grogbáró",
        "to_battle": "Megküzdünk vele",
        "Dutch": "holland",
        "info": "Üzenet",
        "game": "Játék",
        "loading_game": "Játék betöltése...",
        "loading_done": "Játék betöltése... Kész!",
        "discard_game": "Már folyamatban van egy játék. Ha újat indítasz, az előző játékból minden elvész, ami nem "
                        "volt mentve. Biztosan új játékot kezdesz?",
        "discard_game_b": "Már folyamatban van egy játék. Ha betöltesz egy másikat, a jelenlegi játékból minden "
                          "elvész, ami nincs mentve. Biztosan a betöltést választod?",
        "start_game": "Játék indítása...",
        "start_game_done": "Játék indítása... Kész!",
        "turn_order": "A játékosok sorrendje:",
        "Pirate": "kalóz",
        "card_discard": "Lap eldobása",
        "card_keep": "Lap megtartása",
        "cards": "Kártyák",
        "done": "Kész",
        "port": "Kikötő",
        "miss_turn": "Kimaradok (még %i kör)",
        "miss_turn_last_time": "Kimaradok",
        "treasure": "Kincs",
        "treasure_card": "Kincskártya",
        "dig_for_treasure": "Kincset áshatsz a következő körben.",
        "dig_for_treasure_label": "A kincses szigeten",
        "dig_for_treasure_question": "Továbbmehetsz, vagy átkutathatod kincsért a szigetet. Maradsz a szigeten?",
        "dig_for_treasure_nothing": "Most nem jártál sikerrel.",
        "governor": "Kormányzó",
        "governor_punish": "A birodalom hajóinak elsüllyesztéséért %i körből kimaradsz.",
        "governor_reward": "Az esüllyesztett hajókért a kormányzó %i arany jutalomban részesít.",
        "crew": "Legénység",
        "crew_new": "Új matrózok felbérelése:",
        "crew_ship_full": "A hajó megtelt.",
        "crew_port_empty": "Nincs kit felbérelni.",
        "crew_no_money": "Nincs pénz új matrózokra.",
        "crew_hire": "Felbérel",
        "men_count": "%i matróz %i csapatban",
        "play_leviathan": "Kijátszom a leviatánt",
        "already_bought": "Már megvetted",
        "name_missing": "{}. játékos névtelen maradt!",
        "fight": "Összecsapás!",
        "language": "Nyelv",
        "scores": "Pontszámok",
        "Spanish": "spanyol",
        "translation_missing": "[Hiányzik a megfelelő szöveg fordítása.]",
        "sailors_to_hire": "Felbérelhető matrózok",
        "castaway_no_hope": "Ebben a körben nem tudsz megszabadulni a szigetről.",
        "castaway_success": "Egy hajó felvett a szigetről, és %s kikötőjébe vitt.",
        "calm": "A szélcsend miatt egy körből kimaradsz.",
        "color_missing": "{} még nem választott színt!",
        "sirens": "Vesztettél %i matrózt.",
        "sirens_skipped": "Tiéd a lap, harcban kijátszható.",
        "schooner": "szkúner",
        "taino_one": "Egy barátságos benszülött csatlakozott.",
        "taino_none": "A benszülöttek barátságosan üdvzölnek.",
        "taino_some": "%i barátságos benszülött csatlakozott.",
        "new_turn": "%s köre jön.",
        "new_resolution": "A beállított új felbontás:",
        "new_language": "A magyar nyelvet állítottad be.",
        "driftwood": "Az uszadékban semmi hasznosat nem találsz.",
        "driftwood_success": "Egy arany értékű kincset találtál.",
        "defeated_by_kraken": "A kraken legyőzött.",
        "casualties_of_kraken": "A kraken elragadta %i matrózod, mielőtt legyőzted.",
        "storm_miss_turn": "A vihar tönkretette a vitorlázatot. Kimaradsz egy körből, amíg a legénység megfoltozza.",
        "storm_success": "A viharos szél tovább röpíti hajódat.",
        "storm_sail_damage": "A vihar tönkretette a vitorlázatot. Még szerencse, hogy a raktérben volt "
                             "tartalékvitorla.",
        "flag_invalid": "{} érvénytelen zászlót választott!",
        "flag_missing": "{} még nem választott zászlót!",
        "mutiny_succeeded": "A legénység partra tesz egy szigeten.",
        "mutiny_suppressed": "Egy hangzatos beszéddel magad mögé állítod a matrózokat, és a főkolompost kiteszitek "
                             "egy szigetre.",
        "apply": "Alkalmaz",
        "load_saved_game": "Játék folytatása",
        "exit": "Kilépés",
        "save": "Játék mentése",
        "save_and_exit": "Mentés és kilépés",
        "name_label": "Név:",
        "start_button": "Start",
        "color_label": "Szín:",
        "full_screen": "Teljes képernyő",
        "new_game": "Új játék",
        "flag_label": "Zászló:",
        "leviathan_title": "Leviatán",
        "sirens_title": "Szirének",
        "bobbydick_title": "Bobby Dick",
        "scurvy_title": "Skorbut",
        "mutiny_title": "Zendülés",
        "reefs_title": "Zátonyok",
        "deserters_title": "Dezertőrök",
        "treacherous_mate_title": "Az áruló hadnagy",
        "kraken_title": "Támad a Kraken",
        "grog_riot_title": "Groglázadás",
        "carousal_title": "Tivornya",
        "monkey3_title": "A háromfejű majom",
        "castaways_title": "Hajótöröttek",
        "ghost_ship_title": "Kísértethajó",
        "sail_title": "Sorold fel a vitorla részeit!",
        "freed_slaves_title": "Felszabadított rabszolgák",
        "set_sail_to_portroyal_title": "Irány Port Royal!",
        "set_sail_to_havanna_title": "Irány Havanna!",
        "set_sail_to_martinique_title": "Irány Martinique!",
        "set_sail_to_curacao_title": "Irány Curacao!",
        "set_sail_to_tortuga_title": "Irány Tortuga!",
        "shipwreck_title": "Hajótörés",
        "voodoo_curse_title": "Vuduátok",
        "voodoo_wind_spell_title": "Vudu szélvarázs",
        "tavern_brawl_title": "Verekedés a csapszékben",
        "found_port_title": "Alapíts kalózkikötőt!",
        "competition_title": "Csomózási verseny",
        "compass_title": "Megzavarodott iránytű",
        "luck_title": "Horgászszerencse",
        "breath_title": "Lélegzetvisszatartó-\nverseny",
        "pirate_map_0_title": "Kincses térkép",
        "pirate_map_1_title": "Kincses térkép",
        "leviathan_text": "Az ijesztő tengeri kígyó már-már ráveti magát hajódra, amikor egy ősz matróz szigorúan "
                          "legorombítja. A szörnyeteg ettől kezes jószággá válik.\nA játékos akkor is dobhat, ha "
                          "kimaradna, mert a szörny tovább vontatja. Egyszer használható.",
        "sirens_text": "Egy közeli szirt irányából különös dal csendül, amely megzavarja a legénységet.",
        "bobbydick_text": "Az óriás ámbráscet egy szigonytól kínlódik. Eldöntheted, hogy elejted vagy segítesz rajta.",
        "scurvy_text": "A fedélzeten skorbutjárvány tör ki. Minden körben egy matrózt veszítesz, amíg Föld! Föld! "
                       "mezőre vagy kikötőre nem lépsz.",
        "mutiny_text": "A fedélzeten zendülés tör ki.",
        "reefs_text": "Hajód zátonyok közt halad át.|Hajód megfeneklett, amikor a zátonyok közt lavíroztál. Egy körből"
                      " kimaradsz.",
        "deserters_text": "Az egyik csónak eltűnt az éjjel. | fő elszökött a legénységből.",
        "treacherous_mate_text": "Egy félrebeszélő hajótöröttben a Grogbáró nevű hajó szökött hadnagyára ismersz. A "
                                 "halála előtti utolsó tiszta pillanatban még elmondja, hogyan lehet megtalálni a "
                                 "kalózkirály kincsét a szigeten, amelynek koordinátáit nem ismeri, csak maga "
                                 "Harrison kapitány.",
        "kraken_text": "A mélytengerek réme hajódat szemelte ki főfogásnak.",
        "grog_riot_text": "A tengerész szeszesital feliratú hordókban csak hitvány lötty van. A tengeri medvék "
                          "kijózanodnak. Tartsd meg a kártyát a következő körig. Ha sikerül egy kikötőbe jutnod, a "
                          "kártya eldobható. Ha nem, kitör a zendülés.",
        "carousal_text": "Davy Jones születésnapja alkalmából a legénység hatalmas tivornyát rendez. A plusz adag "
                         "grog fellelkesíti őket, ezért, ha a következő körben hajózáshoz dobott érték kedvezőtlen, "
                         "egyszer újra dobhatsz helyette.",
        "monkey3_text": "Az árbockosárban ülő matróz egy háromfejű majmot vél látni a közeli feltérképezetlen "
                        "szigeten. A legénység partra száll, de semmiféle majmot nem találnak.",
        "castaways_text": "Hajótörötteket találsz egy szigeten. | fő csatlakozott.",
        "ghost_ship_text": "Egy legénység nélküli hajót csáklyáztok meg. A legénységedből | főnek rejtélyesen nyoma "
                           "vész, viszont a fedélzeten kincset találsz.",
        "sail_text": "A Kalózok Rendelkezéseinek  Egységes Szabályzata (KRESZ) szerint a vitorla egy nagy darab "
                     "vitorlavászonból áll. Ha jól felsoroltad - és legénységed elhiszi, hogy így történt -, újra te "
                     "jössz.",
        "freed_slaves_text": "Hajód elfog sodródó slavert. A legénységnek titokzatos módon nyoma veszett, de "
                             "rabszolgák némelyike még él. | fő csatlakozott a legénységhez.",
        "set_sail_to_portroyal_text": "None",
        "set_sail_to_havanna_text": "None",
        "set_sail_to_martinique_text": "None",
        "set_sail_to_curacao_text": "None",
        "set_sail_to_tortuga_text": "None",
        "shipwreck_text": "Választhatsz, hogy kimaradsz három körből, amíg a legénységet újra összegyűjtöd egy új "
                          "hajó fedélzetén, vagy lemondasz róluk, és kiúszol a száműzöttek szigetére.",
        "voodoo_curse_text": "Egy vudu varázsló átkot mondott a hajódra. Legközelebb ha kincset kell húznod, hagyd "
                             "ki, és helyette dobd el az átok kártyát.",
        "voodoo_wind_spell_text": "Egy vudu pap jó szelet kér számodra a szellemektől. Tedd el a kártyát, és egyszer "
                                  "tetszés szerint elforgathatod a szélirány mutatóját lépés előtt.",
        "tavern_brawl_text": "Egy összeszólalkozást követően ölre mentek embereid a csapszékében.",
        "found_port_text": "Egyre többen ismerik a neved a Karib-tengeren. Kedvenc horgonyzóhelyed egyre népszerűbb.",
        "competition_text": "Fogadtál a fedélzetmesterrel, hogy gyorsabban kötsz matrózcsomót, mint ő.",
        "compass_text": "Nem a szigetek mentek arrébb, hanem az iránytű rossz. Egy körből kimaradsz, amíg a csillagok "
                        "alapján tájolva visszakormányozzátok a hajót a helyes irányba.",
        "luck_text": "None",
        "breath_text": "Megvan a lélegzetvisszatartó-verseny győztese. Vesztettél egy matrózt.",
        "pirate_map_0_text": "Egy kincs helyét felfedő térképre akadtál. Tartsd meg a kártyát, amíg a déli kincses "
                             "szigetre nem vetődsz, és ott egyből beválthatod kincsre. Utána viszont már nem áshatsz "
                             "le másik kincsért a következő körben.",
        "pirate_map_1_text": "Egy kincs helyét felfedő térképre akadtál. Tartsd meg a kártyát, amíg az északnyugati "
                             "kincses szigetre nem vetődsz, és ott egyből beválthatod kincsre. Utána viszont már nem "
                             "áshatsz le másik kincsért a következő körben.",
        "treasure_title": "Kincs",
        "treasure_text": "Találtál {} aranyat.",
        "greek_fire_title": "Görögtűz",
        "greek_fire_text": "Szétszór egy választott ellenséges csapatot. Egyszer használható csatánként.",
        "grenade_title": "Gránát",
        "grenade_text": "Elsöpör egy tetszőleges ellenséges csapatot. Egyszer használható.",
        "grapeshot_title": "Kartács",
        "grapeshot_text": "Minden csapatod ágyúból tüzel az ellenfélre, aki nem támad vissza.",
        "dog_title": "Kutya",
        "dog_text": "None",
        "caltrop_title": "Lábtövis",
        "caltrop_text": "Az ellenfél a csata végéig hátránnyal harcol. Egyszer használható.",
        "monkey_title": "Majom",
        "monkey_text": "Megszerzi a kincset a süllyedő ellenséges hajóról.",
        "parrot_title": "Papagáj",
        "parrot_text": "None",
        "gun_title": "Pisztoly",
        "gun_text": "Egy töltött pisztoly mindig jól jön a csatában.",
        "rifle_title": "Puska",
        "rifle_text": "Tovább tart megtölteni, mint egy pisztolyt, de pontosabb is.",
        "sirenhorn_title": "Szirénkürt",
        "sirenhorn_text": "Minden ellenséges csapatból egy fő átáll a játékoshoz.",
        "map_title": "Térkép",
        "map_text": "None",
        "spare_sail_title": "Tartalékvitorla",
        "spare_sail_text": "None",
        "hawke_title": "Jane Hawke",
        "hawke_text": "Amíg útitársként a hajón van, a legénység fejében a lázadás gondolata sem fordul meg.",
        "fuil_title": "Peter Fuil",
        "fuil_text": "Amíg útitársként a hajón van, a játékos sebesült matrózai közül meg tud menteni párat.",
        "lopez_title": "Maria Lopez",
        "lopez_text": "Amíg útitársként a hajón van, a játékos minden esetben választhat a kincspakli két legfelső "
                      "lapja közül.",
        "alvarez_title": "Juan Alvarez",
        "alvarez_text": "Amíg útitársként a hajón van, csatánként egyszer újrarendezhetőek a csapatok.",
        "vandenbergh_title": "Anna van den Bergh",
        "vandenbergh_text": "Amíg útitársként a hajón van, minden kikötőben két fővel több matrózt bérelhet a "
                            "játékos.",
        "molenaar_title": "Thomas Molenaar",
        "molenaar_text": "Amíg útitársként a hajón van, a matrózok olcsóbban bérelhetőek.",
        "therese_title": "Thérése",
        "therese_text": "Amíg útitársként a hajón van, a legénységen sosem vesz erőt a skorbut.",
        "levasseur_title": "Jacques Levasseur",
        "levasseur_text": "Amíg útitársként a hajón van, erősebb viharban is kormányozható a hajó.",
        "lizzy_title": "Lizzy",
        "lizzy_text": "A kalózkirály egyetlen leánya.",
        "billy_title": "Billy",
        "billy_text": "Pontosabb ágyúzást tesz lehetővé."
    }
