from .localization import Localization


class Pirate(Localization):
    name = "Kalóz"
    _terms = {
        "this_language": name,
        "British": "könyörtelen angol",
        "price": "Ár",
        "gold": "arany",
        "balance_teams": "Mindenki a heléyre!",
        "settings": "Fedélköz",
        "bermuda": "A Bermuda-háromszög szélén a tenger csendes. Arr... Sehol egy hajó!",
        "brigantine": "brigantin",
        "aiming": "Célozz!",
        "whalevsoctopus": "megküzd vele",
        "title": "A kalózkirály kincse - Vedd el, ami kell, és vissza ne add!",
        "battle": "Harc",
        "leave_battle": "Gyáva megfutamodás",
        "leave_battle_text": "Ha bezárod ezt a képernyőt, elveszíted a matrózaid, és a száműzöttek szigetére kerülsz. "
                             "Biztosan ezt szeretnéd?",
        "battle_sink": "Az ellenséges hajót a fenékre küldtük.",
        "battle_lose": "Veszítettél. Ellenfeleid fogságba ejtettek, és a Száműzöttek szigetén tettek partra.",
        "event_card": "Eseménykártya",
        "extra": "Válaszd ki, melyik ellenséges csapat ellen indítasz extra támadást!",
        "resolution": "Mérrret",
        "land": "Amíg a többiek vannak soron, matrózaid gyümölcsöket és szárnyasokat gyűjtenek be az érintetlen "
                "szigetről. A friss koszt fellelkesíti őket, ezért, ha a következő körben hajózáshoz dobott érték "
                "kedvezőtlen, egyszer újra dobhatsz helyette.",
        "land_log": "Újra dobhat, uram, ehelyett.",
        "tavern": "Csapszék",
        "French": "puhány francia",
        "frigate": "fregatt",
        "main_main": "Árboc",
        "galleon": "galleon",
        "shipwright": "Hajóács",
        "ship_spotted": "Hajó a láthatáron! Mit tegyünk, kapitány?",
        "ship_spotted_fire": "Pörköljünk oda!",
        "ship_spotted_alvarez": "Rendezze újra az embereit, uram!",
        "ship_spotted_battle_starts": "Játssz ki egy lapot, vagy harcolj.",
        "ship_spotted_let_them_flee": "Ne törődjetek vele",
        "ship_spotted_battle": "Kapitány, állítsa össze a csapatokat a harc előtt.",
        "ship_spotted_reward": "Megkaparintottunk %i aranyat%s.",
        "ship_spotted_reward2": " és egy kincskártyát",
        "ship_spotted_pirate": "Hajó a láthatáron! Felénk tart, kapitány.",
        "ship_spotted_powder_storage": "Az ellenséges hajó lőporraktára felrobbant.",
        "ship_spotted_boarding": "Csáklyákat készenlétbe!",
        "ship_spotted_fleeing": "Menküljünk!",
        "ship_spotted_fleeing_unsuccesful": "Nem tudjuk lehagyni őekt, készüljünk a közelharcra!",
        "ship_spotted_parrot": "Papagájod megszerezte az ellenséges hajó kincsét!\\n",
        "ship_spotted_enemy_casualties": "Az ellenfél %i matrózt veszített az ágyúzás során.",
        "ship_spotted_player_casualties": "2 matrózt vesztettünk az ágyúzás során, uram.",
        "ship_spotted_enemy_sinking": "Léket ütöttünk az ellenséges hajó, uram. 3 kör és elsüllyed.",
        "ship_name_player": "Saját hajód",
        "ship_name_pirate0": "Fekete Sikoly",
        "ship_name_pirate1": "Vérszínű Bárka",
        "ship_name_pirate2": "Végzet",
        "ship_name_pirate3": "Grogbáró",
        "to_battle": "Harcra!",
        "Dutch": "pohos holland",
        "info": "Palackposta",
        "game": "Főfedélzet",
        "loading_game": "Kötélzet kibogozása...",
        "loading_done": "Kötélzet kibogozása... Kész!",
        "discard_game": "Teringettét, már kihajóztunk egyszer! Ha újra megtesszük, a korábbi út lejegyzetlen "
                        "eredményei elvesznek. Hótbiztos kihajózzunk, kapitány?",
        "discard_game_b": "Teringettét, ha hajót váltunk, a jelenlegi zsákmány elmentetlen része odavész. Hótbiztos "
                          "átszállunk, kapitány?",
        "start_game": "Mindenki a fedélzetre, kihajózunk!",
        "start_game_done": "Kihajóztunk!",
        "turn_order": "Csak sorjában, matrózok:",
        "Pirate": "kalóz",
        "card_discard": "Eldobom",
        "card_keep": "Megtartom",
        "cards": "Kártyák",
        "done": "Ennyit erről",
        "port": "Kikötő",
        "miss_turn": "Kimaradunk (még %i kör)",
        "miss_turn_last_time": "Kimaradunk",
        "treasure": "Zsákmány",
        "treasure_card": "Kincskártya",
        "dig_for_treasure": "Ez egy kincses sziget, kapitány!",
        "dig_for_treasure_label": "A kincses szigeten",
        "dig_for_treasure_question": "Tovább is mehetünk. Maradjunk kincsetkeresni, uram?",
        "dig_for_treasure_nothing": "Semmit sem találtunk, uram.",
        "governor": "Kormányzó",
        "governor_punish": "Kalózkodás vétkéért %i kör börtönbüntetést kapsz. Legközelebb ne számíts irgalmora, ha a "
                           "birodalmunk hajóit fosztogatod!",
        "governor_reward": "Áldásos tevékenyégedért %i aranytallér üti a markodat.",
        "crew": "Matrózok",
        "crew_new": "Hány fő kell még, kapitány?",
        "crew_ship_full": "Tele a hajó, kapitány!",
        "crew_port_empty": "A csapszék üres.",
        "crew_no_money": "Nincs pénzünk újakra, kapitány.",
        "crew_hire": "Johó!",
        "men_count": "%i matróz %i csapatban",
        "play_leviathan": "Majd a szörny segít!",
        "already_bought": "Már megszereztük",
        "name_missing": "{}. matróz, mi a neved?",
        "fight": "Harcra!",
        "language": "Nyelv...arr...",
        "scores": "Davy Jones ládája",
        "Spanish": "gaz spanyol",
        "translation_missing": "[Kapitány, ezen a nyelven ezt nem tudom elmondani.]",
        "sailors_to_hire": "Tettrekész legények",
        "castaway_no_hope": "Ebben a körben nem tudsz megszabadulni a szigetről.",
        "castaway_success": "Egy hajó felvett a szigetről, és %s kikötőjébe vitt.",
        "calm": "A szélcsend miatt egy körből kimaradunk, uram.",
        "color_missing": "{}, válassz színt, de még ma!",
        "sirens": "%i matróz a vízbe vetette magát, uram.",
        "sirens_skipped": "Egy szirént befogtunk, uram!",
        "schooner": "szkúner",
        "taino_one": "Egy benszülött csatlakozott hozzánk, uram.",
        "taino_none": "Benszülötteket láttunk, uram.",
        "taino_some": "%i benszülött csatlakozott hozzánk, uram.",
        "new_turn": "%s köre jön.",
        "new_resolution": "Zsákmányod egy új felbontás:",
        "new_language": "A legénység kalózok módjára beszél, johó!",
        "driftwood": "Az uszadékban semmi hasznos nem volt, uram!",
        "driftwood_success": "Egy arany értékű kincset találtunk, uram.",
        "defeated_by_kraken": "A kraken legyőzött minket, uram.",
        "casualties_of_kraken": "A kraken elragadott %i matrózt, mielőtt legyőztük, uram.",
        "storm_miss_turn": "A vihar tönkretette a vitorlázatot. Kimaradsz egy körből, amíg a legénység megfoltozza.",
        "storm_success": "A viharos szél tovább röpíti hajódat.",
        "storm_sail_damage": "A vihar tönkretette a vitorlázatot. Még szerencse, hogy a raktérben volt "
                             "tartalékvitorla.",
        "flag_invalid": "{}, válassz zászlót, de érvényeset!",
        "flag_missing": "{}, válassz zászlót, de még ma!",
        "mutiny_succeeded": "A matrózaid egy isten háta mögötti szigeten hagynak.",
        "mutiny_suppressed": "Miután rendre utasítottad a kutyákat, a pallóra tereled a vezérüket.",
        "apply": "Hajrá",
        "load_saved_game": "Folytassuk, kalózok!",
        "exit": "Takarodó",
        "save": "Jegyezzük föl",
        "save_and_exit": "Jegyezd meg és tünés",
        "name_label": "Neved:",
        "start_button": "Hajrá!",
        "color_label": "Vitorla:",
        "full_screen": "Vitorlát bonts!",
        "new_game": "Tengerre, semmirekellők!",
        "flag_label": "Lobogó:",
        "leviathan_title": "Leviatán",
        "sirens_title": "Szirének",
        "bobbydick_title": "Bobby Dick",
        "scurvy_title": "Skorbut",
        "mutiny_title": "Zendülés",
        "reefs_title": "Zátonyok",
        "deserters_title": "Dezertőrök",
        "treacherous_mate_title": "Az áruló hadnagy",
        "kraken_title": "Támad a Kraken",
        "grog_riot_title": "Groglázadás",
        "carousal_title": "Tivornya",
        "monkey3_title": "A háromfejű majom",
        "castaways_title": "Hajótöröttek",
        "ghost_ship_title": "Kísértethajó",
        "sail_title": "Sorold fel a vitorla részeit!",
        "freed_slaves_title": "Felszabadított rabszolgák",
        "set_sail_to_portroyal_title": "Irány Port Royal!",
        "set_sail_to_havanna_title": "Irány Havanna!",
        "set_sail_to_martinique_title": "Irány Martinique!",
        "set_sail_to_curacao_title": "Irány Curacao!",
        "set_sail_to_tortuga_title": "Irány Tortuga!",
        "shipwreck_title": "Hajótörés",
        "voodoo_curse_title": "Vuduátok",
        "voodoo_wind_spell_title": "Vudu szélvarázs",
        "tavern_brawl_title": "Verekedés a csapszékben",
        "found_port_title": "Alapíts kalózkikötőt!",
        "competition_title": "Csomózási verseny",
        "compass_title": "Megzavarodott iránytű",
        "luck_title": "Horgászszerencse",
        "breath_title": "Lélegzetvisszatartó\n-verseny",
        "pirate_map_0_title": "Kincses térkép",
        "pirate_map_1_title": "Kincses térkép",
        "leviathan_text": "Az ijesztő tengeri kígyó már-már ráveti magát hajódra, amikor egy ősz matróz szigorúan "
                          "legorombítja. A szörnyeteg ettől kezes jószággá válik.\nA játékos akkor is dobhat, ha "
                          "kimaradna, mert a szörny tovább vontatja. Egyszer használható.",
        "sirens_text": "Egy közeli szirt irányából különös dal csendül, amely megzavarja a legénységet.",
        "bobbydick_text": "Az óriás ámbráscet egy szigonytól kínlódik. Eldöntheted, hogy elejted vagy segítesz rajta.",
        "scurvy_text": "A fedélzeten skorbutjárvány tör ki. Minden körben egy matrózt veszítesz, amíg Föld! Föld! "
                       "mezőre vagy kikötőre nem lépsz. ",
        "mutiny_text": "A legénység fellázadt.",
        "reefs_text": "Hajód zátonyok közt halad át.|A hajó homokpadra futott, uram. Kimaradunk egy körből.",
        "deserters_text": "Az egyik csónak eltűnt az éjjel. | fő megszökött, uram.",
        "treacherous_mate_text": "Egy félrebeszélő hajótöröttben a Grogbáró nevű hajó szökött hadnagyára ismersz. "
                                 "A halála előtti utolsó tiszta pillanatban még elmondja, hogyan lehet megtalálni a "
                                 "kalózkirály kincsét a szigeten, amelynek koordinátáit nem ismeri, csak maga "
                                 "Harrison kapitány.",
        "kraken_text": "A mélytengerek réme hajódat szemelte ki főfogásnak. ",
        "grog_riot_text": "A tengerész szeszesital feliratú hordókban csak hitvány lötty van. A tengeri medvék "
                          "kijózanodnak. Tartsd meg a kártyát a következő körig. Ha sikerül egy kikötőbe jutnod, a "
                          "kártya eldobható. Ha nem, kitör a zendülés.",
        "carousal_text": "Davy Jones születésnapja alkalmából a legénység hatalmas tivornyát rendez. A plusz  adag "
                         "grog fellelkesíti őket, ezért, ha a következő körben hajózáshoz dobott érték kedvezőtlen, "
                         "egyszer újra dobhatsz helyette.",
        "monkey3_text": "Az árbockosárban ülő matróz egy háromfejű majmot vél látni a közeli feltérképezetlen "
                        "szigeten. A legénység partra száll, de semmiféle majmot nem találnak.",
        "castaways_text": "Hajótörötteket találsz egy szigeten. | fő csatlakozott.",
        "ghost_ship_text": "Egy legénység nélküli hajót csáklyáztunk meg, uram. | főnek rejtélyesen nyoma veszett, "
                           "viszont a fedélzeten kincset találtunk.",
        "sail_text": "A Kalózok Rendelkezéseinek  Egységes Szabályzata (KRESZ) szerint a vitorla egy nagy darab "
                     "vitorlavászonból áll. Ha jól felsoroltad - és legénységed elhiszi, hogy így történt , újra te "
                     "jössz.",
        "freed_slaves_text": "Hajód elfog sodródó slavert. A legénységnek titokzatos módon nyoma veszett, de "
                             "rabszolgák némelyike még él. | fő csatlakozott a legénységhez, uram.",
        "set_sail_to_portroyal_text": "None",
        "set_sail_to_havanna_text": "None",
        "set_sail_to_martinique_text": "None",
        "set_sail_to_curacao_text": "None",
        "set_sail_to_tortuga_text": "None",
        "shipwreck_text": "Választhatsz, hogy kimaradsz három körből, amíg a legénységet újra összegyűjtöd egy új "
                          "hajó fedélzetén, vagy lemondasz róluk, és kiúszol a száműzöttek szigetére.",
        "voodoo_curse_text": "Egy vudu varázsló átkot mondott a hajódra. Legközelebb ha kincset kell húznod, hagyd "
                             "ki, és helyette dobd el az átok kártyát.",
        "voodoo_wind_spell_text": "Egy vudu pap jó szelet kér számodra a szellemektől. Tedd el a kártyát, és egyszer "
                                  "tetszés szerint elforgathatod a szélirány mutatóját lépés előtt.",
        "tavern_brawl_text": "Egy összeszólalkozást követően ölre mentek embereid a csapszékében.",
        "found_port_text": "Egyre többen ismerik a neved a Karib-tengeren. Kedvenc horgonyzóhelyed egyre népszerűbb.",
        "competition_text": "Fogadtál a fedélzetmesterrel, hogy gyorsabban kötsz matrózcsomót, mint ő.",
        "compass_text": "Nem a szigetek mentek arrébb, hanem az iránytű rossz. Egy körből kimaradsz, amíg a csillagok "
                        "alapján tájolva visszakormányozzátok a hajót a helyes irányba.",
        "luck_text": "None",
        "breath_text": "Megvan a lélegzetvisszatartó-verseny győztese. Vesztettél egy matrózt.",
        "pirate_map_0_text": "Egy kincs helyét felfedő térképre akadtál. Tartsd meg a kártyát, amíg a déli kincses "
                             "szigetre nem vetődsz, és ott egyből beválthatod kincsre. Utána viszont már nem áshatsz "
                             "le másik kincsért a következő körben.",
        "pirate_map_1_text": "Egy kincs helyét felfedő térképre akadtál. Tartsd meg a kártyát, amíg az északnyugati "
                             "kincses szigetre nem vetődsz, és ott egyből beválthatod kincsre. Utána viszont már nem "
                             "áshatsz le másik kincsért a következő körben.",
        "treasure_title": "Zsákmány",
        "treasure_text": "Zsákmányod {} arany.",
        "greek_fire_title": "Görögtűz",
        "greek_fire_text": "Szétkergeti az ellenséget.",
        "grenade_title": "Gránát",
        "grenade_text": "A pokolra küldi az ellenséget.",
        "grapeshot_title": "Kartács",
        "grapeshot_text": "Minden csapatod ágyúból tüzel az ellenfélre, aki nem támad vissza.",
        "dog_title": "Kutya",
        "dog_text": "None",
        "caltrop_title": "Lábtövis",
        "caltrop_text": "Leszűkíti harcban az ellenfél mozgásterét.",
        "monkey_title": "Majom",
        "monkey_text": "Jack, a majom elhozza a süllyedő hajókról a kincset.",
        "parrot_title": "Papagáj",
        "parrot_text": "None",
        "gun_title": "Pisztoly",
        "gun_text": "Tölts, és lőj!",
        "rifle_title": "Puska",
        "rifle_text": "Tölts, tölts, lőj!",
        "sirenhorn_title": "Szirénkürt",
        "sirenhorn_text": "Minden ellenséges csapatból egy fő átáll a játékoshoz.",
        "map_title": "Térkép",
        "map_text": "None",
        "spare_sail_title": "Tartalékvitorla",
        "spare_sail_text": "None",
        "hawke_title": "Jane Hawke",
        "hawke_text": "Amíg útitársként a hajón van, a legénység fejében a lázadás gondolata sem fordul meg.",
        "fuil_title": "Peter Fuil",
        "fuil_text": "Megment néhány matrózt csata után.",
        "lopez_title": "Maria Lopez",
        "lopez_text": "Amíg útitársként a hajón van, a játékos minden esetben választhat a kincspakli két legfelső "
                      "lapja közül.",
        "alvarez_title": "Juan Alvarez",
        "alvarez_text": "Amíg útitársként a hajón van, csatánként egyszer újrarendezhetőek a csapatok.",
        "vandenbergh_title": "Anna van den Bergh",
        "vandenbergh_text": "Amíg útitársként a hajón van, minden kikötőben két fővel több matrózt bérelhet a "
                            "játékos.",
        "molenaar_title": "Thomas Molenaar",
        "molenaar_text": "Amíg útitársként a hajón van, a matrózok olcsóbban bérelhetőek.",
        "therese_title": "Thérése",
        "therese_text": "Amíg útitársként a hajón van, a legénységen sosem vesz erőt a skorbut.",
        "levasseur_title": "Jacques Levasseur",
        "levasseur_text": "Amíg útitársként a hajón van, erősebb viharban is kormányozható a hajó.",
        "lizzy_title": "Lizzy",
        "lizzy_text": "A kalózkirály egyetlen leánya.",
        "billy_title": "Billy",
        "billy_text": "Pontosabb ágyúzást tesz lehetővé."
    }
