from enum import auto
from extensions import AutoNamedEnum


class EventCardTypes(AutoNamedEnum):
    bobbydick = auto()
    breath = auto()
    carousal = auto()
    castaways = auto()
    compass = auto()
    competition = auto()
    deserters = auto()
    found_port = auto()
    freed_slaves = auto()
    ghost_ship = auto()
    grog_riot = auto()
    kraken = auto()
    leviathan = auto()
    luck = auto()
    monkey3 = auto()
    mutiny = auto()
    pirate_map_0 = auto()
    pirate_map_1 = auto()
    reefs = auto()
    sail = auto()
    set_sail_to_curacao = auto()
    set_sail_to_havanna = auto()
    set_sail_to_martinique = auto()
    set_sail_to_portroyal = auto()
    set_sail_to_tortuga = auto()
    shipwreck = auto()
    sirens = auto()
    scurvy = auto()
    tavern_brawl = auto()
    treacherous_mate = auto()
    voodoo_curse = auto()
    voodoo_wind_spell = auto()
